### ISSUE TITLE
Performance optimisation

### ISSUE THREAD

**Issue by dylmye** [uk-x-gov-software-community/xgov-opensource-repo-scraper#1]
Hi,

Obviously as this project is handling a large-ish dataset, it takes a long time to load. Would you be opposed to me making a PR to fix this? :) I can see either pagination or something like [Clusterize](https://clusterize.js.org/) coming in handy.

Edit: also is there any CLA or anything I have to agree to when contributing to UKHomeOffice/xgov? Thanks

**Comment by chrisns** [comment]
hi @dylmye sorry! didn't see this at all
Feel free to make PR, no CLA required
Thanks!

**Comment by chrisns** [comment]
Hey @dylmye closing this for now. But if you’re still up for it, a PR would be awesome!
